---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: hello-rc
spec: 
  replicas: 3
  template: 
    metadata: 
      name: hello-pod
    spec: 
      containers: 
        - image: ngnix:1
          name: ngnix
          ports: 
            - containerPort: 80  
